import {
  ActionButton,
  AboutSection,
  Button,
  Card,
  Container,
  ContactForm,
  DynamicSection,
  FAQAccordion,
  FacultyGrid,
  Grid,
  Heading,
  HeroBanner,
  HeroCTAButton,
  HeroHeading,
  HeroSubheading,
  Image,
  Paragraph,
  RawHTML,
  Section,
  Spacer,
  Statistics,
  TextBlock,
  Video,
} from "../builder-components";

type GenericComponentProps = Record<string, unknown>;

export const ComponentMapper: Record<
  string,
  React.ComponentType<GenericComponentProps>
> = {
  HeroBanner,
  HeroHeading,
  HeroSubheading,
  HeroCTAButton,
  TextBlock,
  Container,
  Section,
  Grid,
  Image,
  Video,
  AboutSection,
  Statistics,
  FacultyGrid,
  FAQAccordion,
  ContactForm,
  DynamicSection,
  Button,
  ActionButton,
  RawHTML,
  Card,
  Heading,
  Paragraph,
  Spacer,
};
